package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '03DeployToStaging'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("03DeployToStaging")) {
    triggers {
        remove {
            vcs {
                branchFilter = ""
            }
        }
    }

    dependencies {
        expect(RelativeId("02Chrome")) {
            snapshot {
            }
        }
        update(RelativeId("02Chrome")) {
            snapshot {
                reuseBuilds = ReuseBuilds.NO
                onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }

        expect(RelativeId("03Firefox")) {
            snapshot {
            }
        }
        update(RelativeId("03Firefox")) {
            snapshot {
                reuseBuilds = ReuseBuilds.NO
                onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }

    }
}
